spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
